### PR TITLE
Implemented user jcalazan's fix for an issue, and ran tests, closes #321

### LINKED ISSUE #321: 'TaggableRel' object has no attribute 'through_fields' in Django 1.8.2
When I try to open admin page, it crashes with `TaggableRel' object has no attribute 'through_fields'`.
I can add this attribute to TaggableRel class to fix this error, but to be honest I have no idea is it ok to do it in that way.

### PR DESCRIPTION
**Pull request by scrummyin**
In response to https://github.com/alex/django-taggit/issues/321

### CODE REVIEW

**Comment by frewsxcv** [comment]
Assuming the tests pass, I'll be happy to merge this. Though, if you want commit credit, you'll need to [follow these steps](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/). Otherwise, the commit just has your first+last name and not associated with your GitHub account

**Comment by scrummyin** [comment]
I don't need commit credit, the credit should go to jcalazan anyway. I just implemented his fix, so go please feel free to merge it anyway you see fit.

**Comment by frewsxcv** [comment]
Sounds good, thanks @scrummyin !

**Comment by frewsxcv** [comment]
Fixed in #328 

Just published 0.16.2 that includes the fix

https://pypi.python.org/pypi/django-taggit/0.16.2

**Pull request merged**
