### PR TITLE
Fix #272 (wrong slugs for non-latin chars)

### LINKED ISSUE #272: Unicode tags do not have correct slugs
When adding greek tags  I get wrong slugs: The first greek tag gets an empty slug while the next ones get _1, _2, _3 etc. This behavior can be fixed by including unidecode and modifying line 79 of models.py from ``slug = default_slugify(tag)`` to ``slug = unidecode.unidecode(default_slugify(tag))``.

Unidecode is a nice library that translates non-latin strings to their equivalent latin ones. For instance,

<pre>
import unidecode
unidecode.unidecode(u'δοκιμή') # 'dokime'
unidecode.unidecode(u'greek ελληνικά') # 'greek ellenika'
</pre>

I have to notice that this (translating non-latin characters to their latin equivalents) is the behavior that django-admin *also* follows when prepopulating fields for slugs.

If needed I can also provide a PR for this.

### PR DESCRIPTION
**Pull request by spapas**
This PR resolves #272.

### CODE REVIEW

**Comment by yohanboniface** [comment]
Is there any official status of this PR from the maintainers?

I'm interested too to have it merged. And I also think that using unidecode only if installed (as suggested in https://github.com/alex/django-taggit/pull/273#issuecomment-66955534) could be a nice way to keep the default installation light and without deps, and to prevent any licence change issue.

**Comment by frewsxcv** [comment]
It'd be great if this could be a feature one could opt-in to instead of having a library that everyone has to install. Maybe some way for the user to specify a function they want to use to generate a slug? Also, I'm not really a fan of adding a GPL dependency to a BSD licensed library.

**Comment by spapas** [comment]
@frewsxcv I proposed on my 15 December 2014 comment (use a try/catch block to check if unidecode is installed and fall back to normal slugify if it's not bee installed) however I don't want to provide a PR until I know it'll be merged :relaxed:

**Comment by frewsxcv** [comment]
Anyone have opinions on #315 before I merge it?

**Comment by spapas** [comment]
@frewsxcv :+1:

**Comment by frewsxcv** [comment]
#315 has been merged

0.15.0 has been released which includes it https://github.com/alex/django-taggit/blob/develop/CHANGELOG.txt#L4

**Comment by frewsxcv** [comment]
Also, if anyone wants to go above and beyond, we'd probably eventually want a regression test and also a mentioning of the optional dependency (unidecode) in the documentation.

**Pull request closed without merging**
