### PR TITLE
Add support for Django 2.0

### PR DESCRIPTION
**Pull request by jdufresne**
Add Django 2.0 to the Travis and tox test matrix.

Add Django 2.0 to the list of trove classifiers.

Update `TaggableRel` for internal API differences of Django 2.0. Guard with a `VERSION` check where necessary.

### CODE REVIEW

**Comment by jdufresne** [comment]
The test failure is due to the master branch, not Django 2.0. A fix for the travis configuration is in #504.

**Comment by aaugustin** [comment]
Thanks, this branch works well, I'm running it in production now.

**Comment by hggh** [comment]
@alex could you please merge this Django 2 PR into your master and release a new version of taggit?

**Comment by nemesisdesign** [comment]
@jdufresne I've merged #504 and restarted the build

**Comment by nemesisdesign** [comment]
Latest versions of Pytest dropped support for python 3.3, so that build was failing, I pinned down the version of pytest, let's wait for https://travis-ci.org/alex/django-taggit/builds/319130342 to finish.

**Comment by nemesisdesign** [comment]
Ok the python 3.3 build passed after downgrading pytest, I feel confident in merging this now.
BTW I wouldn't mind in dropping support for python 3.3, but I think that decision is not up to me. I'm only an occasional maintainer and I want to operate with the broadest consensus as possible.

**Comment by hggh** [comment]
@nemesisdesign thanks for merging. python 3.3 is eol: https://www.python.org/dev/peps/pep-0398/#x-end-of-life so it's save to drop it.

There is a PR #512

**Comment by nemesisdesign** [comment]
Ok let's do it

**Pull request merged**
