### PR TITLE
Issue #186 tentative fix

### PR DESCRIPTION
**Pull request by vhf**

### CODE REVIEW

**Comment by oliwarner** [comment]
Tests or no, #186 renders django-taggit near-useless on Django>=1.6.1.

The bug **needs** reopening (there are multiple traces now).
 
I don't neccessarily disagree that this patch might not be *the* answer but it certainly makes taggit work for me. It should get more than a "Oh it breaks the tests goawaylol"

**Comment by kminkov** [comment]
Please take a look at the above solution it fixes the problem and shouldn't brake the tests.

**Comment by frewsxcv** [comment]
@kminkov It doesn't pass some tests. Check the Travis CI logs

https://travis-ci.org/alex/django-taggit/builds/35395642

**Comment by kminkov** [comment]
I created a separate pull request to trigger tests execution and all have passed,you can take a look here: 
https://travis-ci.org/alex/django-taggit/builds/57005002

Also from the testing I did so far for this I couldn't notice any problem.

**Comment by kminkov** [comment]
@frewsxcv Please take a look at this pull request I created https://github.com/alex/django-taggit/pull/305 . It contains my changes and passes the tests.

**Comment by frewsxcv** [comment]
Fixed in #305

**Pull request closed without merging**
