### PR TITLE
Fix on_delete warning in django 1.9

### PR DESCRIPTION
**Pull request by collinanderson**

### CODE REVIEW

**Comment by frewsxcv** [comment]
Just released 0.17.2 that has Django 1.9 fixes. Is this PR still necessary?

https://pypi.python.org/pypi/django-taggit/0.17.2

**Comment by collinanderson** [comment]
Currently it raises a warning on 1.9, and will eventually be required: https://docs.djangoproject.com/en/1.9/releases/1.9/#foreignkey-and-onetoonefield-on-delete-argument

**Comment by frewsxcv** [comment]
Reopening to rerun the tests

**Comment by frewsxcv** [comment]
Thanks for your contribution!

**Comment by frewsxcv** [comment]
Just released 0.17.3 that includes this change

**Comment by collinanderson** [comment]
Thanks!

**Pull request merged**
