### PR TITLE
improving query performance (issues #318)

### PR DESCRIPTION
**Pull request by pahaz**
https://github.com/alex/django-taggit/issues/318

### CODE REVIEW

**Comment by jezdez** [comment]
@frewsxcv We've seen slow queries as well and think this could fix a bunch of performance issues with taggit. Can you elaborate what would be needed to finish this?

**Comment by frewsxcv** [comment]
@jezdez I will merge it later today

**Comment by frewsxcv** [comment]
Sorry for the delay. Thanks for your contribution @pahaz!

**Comment by frewsxcv** [comment]
0.17.0 has just been released which includes this change

**Pull request merged**
