### PR TITLE
Add extra_filters argument to the manager's most_common method

### PR DESCRIPTION
**Pull request by payamnj**

### CODE REVIEW

**Comment by frewsxcv** [comment]
Are you able to add a test for this? It could be *very* basic. If not, no worries.

**Comment by payamnj** [comment]
@frewsxcv Yes, I think I can add a test for it.

**Comment by frewsxcv** [comment]
Thanks @payamnj! 🎊

**Comment by frewsxcv** [comment]
Version 0.20.2 has been released which includes this change.

**Comment by payamnj** [comment]
Thanks :)

**Pull request merged**
