### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by auvipy**
first pass.

removed django 1.4-1.6

### CODE REVIEW

**Comment by frewsxcv** [comment]
Don't forget to update the version in the README.

**Comment by auvipy** [comment]
thanks for pointing :D updating

**Comment by auvipy** [comment]
updated

**Comment by frewsxcv** [comment]
Thanks @auvipy!

**Comment by auvipy** [comment]
well come :+1:  check this one https://github.com/alex/django-taggit/pull/387 its passing

**Pull request merged**
